# Deploy a helm chart sourced from another Git repository
# without using pipeline.
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    # Helm chart sourced from another Git repository.
    helmChart:
      gitRemote: git@github.com:pipe-cd/manifests.git
      ref: v0.6.0
      path: manifests/helloworld
    helmOptions:
      valueFiles:
        - values.yaml
      releaseName: helm-remote-git-chart
    helmVersion: 3.1.1
