// Copyright 2024 The PipeCD Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package provider

import "errors"

var (
	ErrNotFound = errors.New("not found")
)

const (
	// labels
	LabelManagedBy          = "pipecd.dev/managed-by"            // Always be piped.
	LabelPiped              = "pipecd.dev/piped"                 // The id of piped handling this application.
	LabelApplication        = "pipecd.dev/application"           // The application this resource belongs to.
	LabelSyncReplace        = "pipecd.dev/sync-by-replace"       // Use replace instead of apply.
	LabelForceSyncReplace   = "pipecd.dev/force-sync-by-replace" // Use replace --force instead of apply.
	LabelServerSideApply    = "pipecd.dev/server-side-apply"     // Use server side apply instead of client side apply.
	LabelCommitHash         = "pipecd.dev/commit-hash"           // Hash value of the deployed commit.
	LabelResourceKey        = "pipecd.dev/resource-key"          // The resource key generated by apiVersion, namespace and name. e.g. apps/v1/Deployment/namespace/demo-app
	LabelOriginalAPIVersion = "pipecd.dev/original-api-version"  // The api version defined in git configuration. e.g. apps/v1

	// annotations
	AnnotationOrder      = "pipecd.dev/order"       // The order number of resource used to sort them before using.
	AnnotationConfigHash = "pipecd.dev/config-hash" // The hash value of all mouting config resources.

	// label/annotation values
	ManagedByPiped     = "piped"
	UseReplaceEnabled  = "enabled"
	UseServerSideApply = "true"
)
