apiVersion: pipecd.dev/v1beta1
kind: CloudRunApp
spec:
  name: analysis
  labels:
    env: example
    team: abc
  pipeline:
    stages:
      # Promote new version to receive amount of traffic.
      - name: CLOUDRUN_PROMOTE
        with:
          percent: 10
      # Optional: We can also add an ANALYSIS stage to verify the new version.
      # If this stage finds any not good metrics of the new version,
      # a rollback process to the previous version will be executed.
      - name: ANALYSIS
        with:
          duration: 10m
          threshold: 2
          https:
            - url: https://canary-endpoint.pipecd.dev
              method: GET
              expected: 200
              interval: 1m
      # Promote new version to receive all traffic.
      - name: CLOUDRUN_PROMOTE
        with:
          percent: 100
  description: |
    This app demonstrates how to use ANALYSIS stage to analyze the deployment.\
    After new version has been deployed to receive 10% of traffic, Piped periodically sends http requests to the endpoint of the new version to verify its responses.\
    References: [adding a new app](https://pipecd.dev/docs/user-guide/adding-an-application/), [app configuration](https://pipecd.dev/docs/user-guide/configuration-reference/)
