# Automatically applies when any changes were detected.
apiVersion: pipecd.dev/v1beta1
kind: TerraformApp
spec:
  input:
    terraformVersion: 0.12.26
  encryption:
    encryptedSecrets:
      serviceAccount: {ENCRYPTED_DATA_GENERATED_FROM_WEB}
    decryptionTargets:
      - .credentials/service-account.json
