# Automatically applies when any changes were detected.
apiVersion: pipecd.dev/v1beta1
kind: TerraformApp
spec:
  name: autorollback
  labels:
    env: example
    team: infra
  input:
    autoRollback: true
  encryption:
    encryptedSecrets:
      serviceAccount: {ENCRYPTED_DATA_GENERATED_FROM_WEB}
    decryptionTargets:
      - .credentials/service-account.json
