area/go:
- cmd/*
- cmd/**/*
- pkg/*
- pkg/**/*

area/web:
- web/*
- web/**/*

area/build:
- hack/*
- .github/*
- .github/**/*
- Makefile
- local/*

area/manifests:
- manifests/**/*

area/examples:
- examples/*
- examples/**/*

area/tool:
- tool/*
- tool/**/*

area/pipedv1:
- pkg/app/pipedv1/**/*
- cmd/pipedv1/**/*
- pkg/plugin/**/*

area/only-pipedv1:
- all: ['pkg/app/pipedv1/**/*', 'cmd/pipedv1/**/*', 'pkg/plugin/**/*']
