area/go:
- cmd/*
- cmd/**/*
- pkg/*
- pkg/**/*

area/web:
- web/*
- web/**/*

area/build:
- hack/*
- .github/*
- .github/**/*
- Makefile
- local/*

area/manifests:
- manifests/**/*

area/examples:
- examples/*
- examples/**/*

area/tool:
- tool/*
- tool/**/*

area/pipedv1:
- pkg/app/pipedv1/**/*
- pkg/configv1/*
- pkg/configv1/**/*

area/plugin-sdk:
- pkg/plugin/sdk/**/*
