apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-by-http
  labels:
    app: analysis-by-http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analysis-by-http
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: analysis-by-http
        pipecd.dev/variant: primary
    spec:
      containers:
      - name: helloworld
        image: gcr.io/pipecd/helloworld:v0.6.0
        args:
          - server
        ports:
        - containerPort: 9085
