linters:
  disable-all: true
  enable:
    - prealloc
    - ineffassign
    - goerr113
    - misspell
    - errcheck
    - gosimple
    - staticcheck
    - gosec
    - gocritic
    - unparam
    - deadcode
    - unconvert
    - typecheck
    - stylecheck
    - exportloopref
  fast: false
linters-settings:
  goimports:
    local-prefixes: github.com/pipe-cd/pipecd

run:
  timeout: 2m
  tests: false
  skip-dirs:
    - "vendor$"
    - "^bazel"
    - pkg/app/api/cmd/samplepipedapicli
    - pkg/app/api/cmd/samplewebapicli
    - pkg/app/api/service/pipedservice/pipedclientfake

issues:
  exclude-rules:
    - linters:
      - gosec
      text: "G204: Subprocess launched"
    - linters:
      - goerr113
      text: "err113: do not define dynamic errors"
    - linters:
      - stylecheck
      text: "ST1003: struct field Https"
    - linters:
      - stylecheck
      text: "ST1003: struct field Id"
