run:
  deadline: 5m
  skip-files:
    - ^.*\.(pb|y)\.go$
  skip-dirs:
    - "vendor$"

linters:
  disable-all: true
  enable:
    - prealloc
    - ineffassign
    - goerr113
    - misspell
    - errcheck
    - gosimple
    - staticcheck
    - gosec
    - gocritic
    - unparam
    - deadcode
    - unconvert
    - typecheck
    - stylecheck
    - exportloopref
    - depguard
    - goimports

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019"

output:
  sort-results: true

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages-with-error-message:
      - sync/atomic: "Use go.uber.org/atomic instead of sync/atomic"
      - io/ioutil: "Use corresponding 'os' or 'io' functions instead."
  goimports:
    local-prefixes: github.com/pipe-cd/pipecd
