{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "piped.configMapName" . }}
  labels:
    {{- include "piped.labels" . | nindent 4 }}
data:
{{- if .Values.quickstart.enabled }}
  {{ .Values.config.fileName }}: |-
    apiVersion: pipecd.dev/v1beta1
    kind: Piped
    spec:
      projectID: quickstart
      pipedID: {{ .Values.quickstart.pipedId }}
      pipedKeyData: {{ .Values.quickstart.pipedKeyData }}
      apiAddress: pipecd:8080
      syncInterval: 1m
      repositories:
        - repoId: examples
          remote: https://github.com/pipe-cd/examples.git
          branch: master
      plugins:
        - name: kubernetes # kubernetes plugin version: v0.3.0
          port: 7001
          url: https://github.com/pipe-cd/pipecd/releases/download/pkg%2Fapp%2Fpipedv1%2Fplugin%2Fkubernetes%2Fv0.3.0/kubernetes_v0.3.0_linux_amd64
          deployTargets:
            - name: kubernetes-local
              config:
                kubectlVersion: 1.33.0
        - name: wait # wait plugin version: v0.1.1
          port: 7002
          url: https://github.com/pipe-cd/pipecd/releases/download/pkg%2Fapp%2Fpipedv1%2Fplugin%2Fwait%2Fv0.1.1/wait_v0.1.1_linux_amd64
{{- else }}
  {{ .Values.config.fileName }}: |-
{{ tpl .Values.config.data . | indent 4 }}
{{- end }}
{{- end }}
