{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "piped.secretName" . }}
  labels:
    {{- include "piped.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
{{- if .Values.secret.kubeConfigs }}
{{- range .Values.secret.kubeConfigs }}
  {{ .fileName | quote }}: {{ .data | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
