apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-patch
  labels:
    app: canary-patch
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary-patch
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: canary-patch
        pipecd.dev/variant: primary
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/pipe-cd/helloworld:v0.30.0
        args:
          - server
        ports:
        - containerPort: 9085
      - name: envoy
        image: envoyproxy/envoy-alpine:v1.18.3
        imagePullPolicy: IfNotPresent
        command:
          - envoy
        args:
          - -c
          - /etc/envoy/envoy-config.yaml
        ports:
          - containerPort: 9090
          - containerPort: 9095
        volumeMounts:
          - name: config
            mountPath: /etc/envoy
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: canary-patch-envoy-config
