apiVersion: pipecd.dev/v1beta1
kind: ECSApp
spec:
  name: secret-management
  input:
    serviceDefinitionFile: servicedef.yaml
    taskDefinitionFile: taskdef.yaml
    targetGroups:
      primary:
        targetGroupArn: arn:aws:elasticloadbalancing:ap-northeast-1:XXXX:targetgroup/ecs-lb/YYYY
        containerName: web
        containerPort: 80
  encryption:
    encryptedSecrets:
      foo: {ENCRYPTED_DATA_GENERATED_FROM_WEB}
    decryptionTargets:
      - servicedef.yaml
