apiVersion: pipecd.dev/v1beta1
kind: CloudRunApp
spec:
  name: secret-management
  labels:
    env: example
    team: abc
  encryption:
    encryptedSecrets:
      key: {ENCRYPTED_DATA_GENERATED_FROM_WEB}
    decryptionTargets:
      - service.yaml
