apiVersion: pipecd.dev/v1beta1
kind: CloudRunApp
spec:
  name: secret-management
  labels:
    env: example
    team: abc
  encryption:
    encryptedSecrets:
      key: {ENCRYPTED_DATA_GENERATED_FROM_WEB}
    decryptionTargets:
      - service.yaml
  description: |
    This app demonstrates how to use [Secret Management](https://pipecd.dev/docs/user-guide/secret-management/) feature to store an encrypted credential in Git for use by Cloud Run service.\
    References: [adding a new app](https://pipecd.dev/docs/user-guide/adding-an-application/), [app configuration](https://pipecd.dev/docs/user-guide/configuration-reference/)
