# Deployment pipeline that contains a manual approval stage.
apiVersion: pipecd.dev/v1beta1
kind: TerraformApp
spec:
  input:
    workspace: dev
    terraformVersion: 0.12.26
  pipeline:
    stages:
      - name: TERRAFORM_PLAN
      - name: WAIT_APPROVAL
      - name: TERRAFORM_APPLY
  encryption:
    encryptedSecrets:
      serviceAccount: {ENCRYPTED_DATA_GENERATED_FROM_WEB}
    decryptionTargets:
      - .credentials/service-account.json
  notification:
    mentions:
      - event: DEPLOYMENT_WAIT_APPROVAL
        slack:
          - U024BE7LH # nghialv
          - U025BE7LK # nakabonne
