# Deployment pipeline that contains a manual approval stage.
apiVersion: pipecd.dev/v1beta1
kind: TerraformApp
spec:
  name: wait-approval
  labels:
    env: example
    team: infra
  input:
    workspace: dev
    terraformVersion: 1.0.10
  pipeline:
    stages:
      - name: TERRAFORM_PLAN
      - name: WAIT_APPROVAL
      - name: TERRAFORM_APPLY
  encryption:
    encryptedSecrets:
      serviceAccount: {ENCRYPTED_DATA_GENERATED_FROM_WEB}
    decryptionTargets:
      - .credentials/service-account.json
  notification:
    mentions:
      - event: DEPLOYMENT_WAIT_APPROVAL
        slack:
          - slack-user-id-1  # slack-user-name-1
          - slack-user-id-2  # slack-user-name-2
      # Specifying "*" means mentioning the given users for all events.
      - event: "*"
        slack:
          - slack-user-id-3  # slack-user-name-3
