{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "api",
    "query": {
     "query": "label_values(envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API - 5xx Error Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum without(envoy_response_code,instance,job) (rate(envoy_cluster_upstream_rq{envoy_response_code=~\"5.*\", job=\"pipecd-gateway\", envoy_cluster_name=~\"$api\"}[5m]))\n/\nsum without(envoy_response_code,instance,job) (rate(envoy_cluster_upstream_rq{job=\"pipecd-gateway\", envoy_cluster_name=~\"$api\"}[5m]))\n* 100"
    }
   ]
  },
  {
   "title": "API - Duration 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum without(instance, job)(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$api\"}[5m]))\n)"
    }
   ]
  },
  {
   "title": "API - Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(envoy_response_code,instance,job) (rate(envoy_cluster_upstream_rq_total{ envoy_cluster_name=~\"$api\"}[5m]))"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Pod - CPU Usage Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (\n  rate(container_cpu_usage_seconds_total{\n    pod=~\"pipecd-server-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)\"\n  }[5m])\n)"
    }
   ]
  },
  {
   "title": "Pod - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (\n  container_memory_usage_bytes{\n    pod=~\"pipecd-server-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)\"\n  }\n)"
    }
   ]
  },
  {
   "title": "Node - CPU Usage Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(kubernetes_node) (rate(node_cpu_seconds_total[5m]))"
    }
   ]
  },
  {
   "title": "Node - Memory Available Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_node) (node_memory_MemAvailable_bytes)"
    }
   ]
  }
 ]
}