{
 "title": "Prometheus Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time Series",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"prometheus\"})"
    }
   ]
  },
  { "title": "HTTP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "99th Quantile of HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum without(instance, job)(rate(prometheus_http_request_duration_seconds_bucket{handler=\"/graph\"}[5m]))\n)",
     "legendFormat": "graph"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum without(instance, job)(rate(prometheus_http_request_duration_seconds_bucket{handler=\"/api/v1/query\"}[5m]))\n)",
     "legendFormat": "query"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum without(instance, job)(rate(prometheus_http_request_duration_seconds_bucket{handler=\"/api/v1/query_range\"}[5m]))\n)",
     "legendFormat": "query_range"
    }
   ]
  },
  {
   "title": "Ingested samples [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[5m])",
     "legendFormat": "localhost"
    }
   ]
  },
  { "title": "Go Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Heap Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"prometheus\"} / (1024 * 1024)",
     "legendFormat": "alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"prometheus\"} / (1024 * 1024)",
     "legendFormat": "inuse"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"prometheus\"} / (1024 * 1024)",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"prometheus\"}",
     "legendFormat": "prometheus"
    }
   ]
  }
 ]
}