{
 "title": "Resource Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "Pod - CPU Usage Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(service) (\n  rate(container_cpu_usage_seconds_total{\n    service=\"$service\"\n  }[5m])\n)"
    }
   ]
  },
  {
   "title": "Pod - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(service) (\n  container_memory_usage_bytes{\n    service=\"$service\"\n  }\n)"
    }
   ]
  },
  {
   "title": "Node - CPU Usage Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(kubernetes_node) (rate(node_cpu_seconds_total[5m]))"
    }
   ]
  },
  {
   "title": "Node - Memory Available Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_node) (node_memory_MemAvailable_bytes)"
    }
   ]
  }
 ]
}