{
 "title": "PipeCD Resource Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  { "title": "Pod Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage of $service Pod [rate-5m]",
   "type": "graph",
   "description": "CPU usage per Pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(service) (\n  rate(container_cpu_usage_seconds_total{\n    service=\"$service\"\n  }[5m]) * 100\n)"
    }
   ]
  },
  {
   "title": "Memory Usage of $service Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(service) (\n  container_memory_usage_bytes{\n    service=\"$service\"\n  } / (1024 * 1024)\n)"
    }
   ]
  },
  { "title": "Node Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n(avg by (instance) (node_memory_MemAvailable_bytes{job=\"kubernetes-service-endpoints\"}) * 100)\n/\n(avg by (instance) (node_memory_MemTotal_bytes{job=\"kubernetes-service-endpoints\"})))"
    }
   ]
  },
  {
   "title": "CPU Cores Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (count(node_cpu_seconds_total{mode=\"system\"}) by (kubernetes_node))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (node_memory_MemTotal_bytes{job=\"kubernetes-service-endpoints\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job) (node_time_seconds{job=\"kubernetes-service-endpoints\"}) \n-\navg by(job) (node_boot_time_seconds{job=\"kubernetes-service-endpoints\"})"
    }
   ]
  },
  {
   "title": "Node - CPU Usage Rate [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_node) (rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Node - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_node) (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / (1024 * 1024 * 1024)"
    }
   ]
  },
  { "title": "Go Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Heap Stats of $service",
   "type": "graph",
   "description": "Heap metrics reported by Go",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (go_memstats_heap_alloc_bytes{job=\"$service\"} / (1024 * 1024))",
     "legendFormat": "alloc"
    },
    {
     "expr": "sum by (job) (go_memstats_heap_inuse_bytes{job=\"$service\"} / (1024 * 1024))",
     "legendFormat": "inuse"
    },
    {
     "expr": "sum by (job) (go_memstats_heap_idle_bytes{job=\"$service\"} / (1024 * 1024))",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Number of Goroutines of $service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (go_goroutines{job=\"$service\"})",
     "legendFormat": "$service"
    }
   ]
  }
 ]
}