{
 "title": "PipeCD Service Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "api",
    "query": {
     "query": "label_values(envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "5xx Error Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum without(envoy_response_code,instance,job) (rate(envoy_cluster_upstream_rq{envoy_response_code=~\"5.*\", job=\"pipecd-gateway\", envoy_cluster_name=\"$api\"}[5m]))\n/\nsum without(envoy_response_code,instance,job) (rate(envoy_cluster_upstream_rq{job=\"pipecd-gateway\", envoy_cluster_name=\"$api\"}[5m]))\n* 100"
    }
   ]
  },
  {
   "title": "Request Duration Quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum without(instance, job)(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$api\"}[5m]))\n)",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum without(instance, job)(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$api\"}[5m]))\n)",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum without(instance, job)(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$api\"}[5m]))\n)",
     "legendFormat": "0.90"
    }
   ]
  },
  {
   "title": "API - Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(envoy_response_code,instance,job) (rate(envoy_cluster_upstream_rq_total{ envoy_cluster_name=\"$api\"}[5m]))",
     "legendFormat": "$api"
    }
   ]
  },
  {
   "title": "Request Size Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upstream_rq_body_size" }
   ]
  },
  {
   "title": "Response Size Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upstream_rs_body_size" }
   ]
  }
 ]
}