apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-steps-canary
  labels:
    app: multi-steps-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-steps-canary
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: multi-steps-canary
        pipecd.dev/variant: primary
    spec:
      containers:
      - name: helloworld
        image: gcr.io/pipecd/helloworld:v0.6.0
        args:
          - server
        ports:
        - containerPort: 9085
