{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipecd.secretName" . }}
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.secret.encryptionKey.data }}
  {{ .Values.secret.encryptionKey.fileName }}: {{ .Values.secret.encryptionKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.firestoreServiceAccount.data }}
  {{ .Values.secret.firestoreServiceAccount.fileName }}: {{ .Values.secret.firestoreServiceAccount.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.gcsServiceAccount.data }}
  {{ .Values.secret.gcsServiceAccount.fileName }}: {{ .Values.secret.gcsServiceAccount.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.cloudSQLServiceAccount.data }}
  {{ .Values.secret.cloudSQLServiceAccount.fileName }}: {{ .Values.secret.cloudSQLServiceAccount.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.minioAccessKey.data }}
  {{ .Values.secret.minioAccessKey.fileName }}: {{ .Values.secret.minioAccessKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.minioSecretKey.data }}
  {{ .Values.secret.minioSecretKey.fileName }}: {{ .Values.secret.minioSecretKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.internalTLSKey.data }}
  {{ .Values.secret.internalTLSKey.fileName }}: {{ .Values.secret.internalTLSKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.internalTLSCert.data }}
  {{ .Values.secret.internalTLSCert.fileName }}: {{ .Values.secret.internalTLSCert.data | b64enc | quote }}
{{- end }}
{{- end }}
