# Quick sync by rolling out the new version and switching all traffic to it.
apiVersion: pipecd.dev/v1beta1
kind: CloudRunApp
spec:
  name: chain-simple-cloudrun
  labels:
    env: example
    team: abc
  trigger:
    onChain:
      disabled: false
