apiVersion: pipecd.dev/v1beta1
kind: LambdaFunction
spec:
  name: InChainSimpleFunction
  role: arn:aws:iam::76xxxxxxx:role/lambda-role
  image: ecr.ap-northeast-1.amazonaws.com/lambda-test:v0.0.1
  memory: 512
  timeout: 30
  environments:
    FOO: bar
  tags:
    app: simple
