apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: analysis-by-log
  labels:
    env: example
    team: product
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 10%
      - name: ANALYSIS
        with:
          duration: 10m
          logs:
            - query: 'logName = "projects/demo/logs/error'
              interval: 1m
              provider: stackdriver-dev
      - name: K8S_PRIMARY_ROLLOUT
      - name: K8S_CANARY_CLEAN
