// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pkg/plugin/api/v1alpha1/planpreview/api.proto

package planpreview

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetPlanPreviewRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPlanPreviewRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPlanPreviewRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPlanPreviewRequestMultiError, or nil if none found.
func (m *GetPlanPreviewRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPlanPreviewRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ApplicationId

	if all {
		switch v := interface{}(m.GetTargetDeploymentSource()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetPlanPreviewRequestValidationError{
					field:  "TargetDeploymentSource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetPlanPreviewRequestValidationError{
					field:  "TargetDeploymentSource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTargetDeploymentSource()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetPlanPreviewRequestValidationError{
				field:  "TargetDeploymentSource",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetPlanPreviewRequestMultiError(errors)
	}

	return nil
}

// GetPlanPreviewRequestMultiError is an error wrapping multiple validation
// errors returned by GetPlanPreviewRequest.ValidateAll() if the designated
// constraints aren't met.
type GetPlanPreviewRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPlanPreviewRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPlanPreviewRequestMultiError) AllErrors() []error { return m }

// GetPlanPreviewRequestValidationError is the validation error returned by
// GetPlanPreviewRequest.Validate if the designated constraints aren't met.
type GetPlanPreviewRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPlanPreviewRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPlanPreviewRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPlanPreviewRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPlanPreviewRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPlanPreviewRequestValidationError) ErrorName() string {
	return "GetPlanPreviewRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetPlanPreviewRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPlanPreviewRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPlanPreviewRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPlanPreviewRequestValidationError{}

// Validate checks the field values on GetPlanPreviewResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPlanPreviewResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPlanPreviewResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPlanPreviewResponseMultiError, or nil if none found.
func (m *GetPlanPreviewResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPlanPreviewResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetResults() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetPlanPreviewResponseValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetPlanPreviewResponseValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetPlanPreviewResponseValidationError{
					field:  fmt.Sprintf("Results[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetPlanPreviewResponseMultiError(errors)
	}

	return nil
}

// GetPlanPreviewResponseMultiError is an error wrapping multiple validation
// errors returned by GetPlanPreviewResponse.ValidateAll() if the designated
// constraints aren't met.
type GetPlanPreviewResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPlanPreviewResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPlanPreviewResponseMultiError) AllErrors() []error { return m }

// GetPlanPreviewResponseValidationError is the validation error returned by
// GetPlanPreviewResponse.Validate if the designated constraints aren't met.
type GetPlanPreviewResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPlanPreviewResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPlanPreviewResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPlanPreviewResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPlanPreviewResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPlanPreviewResponseValidationError) ErrorName() string {
	return "GetPlanPreviewResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetPlanPreviewResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPlanPreviewResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPlanPreviewResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPlanPreviewResponseValidationError{}

// Validate checks the field values on PlanPreviewResult with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PlanPreviewResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PlanPreviewResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PlanPreviewResultMultiError, or nil if none found.
func (m *PlanPreviewResult) ValidateAll() error {
	return m.validate(true)
}

func (m *PlanPreviewResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeployTarget

	// no validation rules for Summary

	// no validation rules for NoChange

	// no validation rules for Details

	if len(errors) > 0 {
		return PlanPreviewResultMultiError(errors)
	}

	return nil
}

// PlanPreviewResultMultiError is an error wrapping multiple validation errors
// returned by PlanPreviewResult.ValidateAll() if the designated constraints
// aren't met.
type PlanPreviewResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PlanPreviewResultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PlanPreviewResultMultiError) AllErrors() []error { return m }

// PlanPreviewResultValidationError is the validation error returned by
// PlanPreviewResult.Validate if the designated constraints aren't met.
type PlanPreviewResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PlanPreviewResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PlanPreviewResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PlanPreviewResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PlanPreviewResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PlanPreviewResultValidationError) ErrorName() string {
	return "PlanPreviewResultValidationError"
}

// Error satisfies the builtin error interface
func (e PlanPreviewResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPlanPreviewResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PlanPreviewResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PlanPreviewResultValidationError{}
