apiVersion: v1
kind: Service
metadata:
  name: multicluster-simple
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: multicluster-simple
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
