apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    manifests:
      - deployment.yaml
      - service.yaml
    kubectlVersion: 1.18.0
  postSync:
    chain:
      applications:
        # The below will match application named `simple` of kind `KUBERNETES`.
        - name: simple
          kind: KUBERNETES
        # The below will match application named `simple` of kind `CLOUDRUN`.
        - name: simple
          kind: CLOUDRUN
