apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: simple
  input:
    manifests:
      - deployment.yaml
      - service.yaml
    kubectlVersion: 1.18.0
  postSync:
    chain:
      applications:
        # The below will match application named `simple` of kind `CLOUDRUN`.
        # which means the app that it's configuration is at
        # https://github.com/pipe-cd/examples/blob/master/cloudrun/simple
        - name: simple
          kind: CLOUDRUN
        # The below will match application named `simple` of kind `LAMBDA`.
        # which means the app that it's configuration is at
        # https://github.com/pipe-cd/examples/tree/master/lambda/simple
        - name: simple
          kind: LAMBDA
