apiVersion: pipecd.dev/v1beta1
kind: ECSApp
spec:
  name: canary
  labels:
    env: example
    team: xyz
  input:
    serviceDefinitionFile: servicedef.yaml
    taskDefinitionFile: taskdef.yaml
    targetGroups:
      # Primary target group is pointed by LB (ALB/NLB) live listener, the Primary task set
      # will be registered to this target group.
      primary:
        targetGroupArn: arn:aws:elasticloadbalancing:ap-northeast-1:XXXX:targetgroup/ecs-canary-blue/YYYY
        containerName: web
        containerPort: 80
      # Canary target group can also be pointed by LB (ALB/NLB) live listener at
      # the beginning of deployment, the Canary task set will be registered to this target group.
      # CAUTION: To enable PipeCD performs canary deployment strategy, this canary target group
      # is required.
      canary:
        targetGroupArn: arn:aws:elasticloadbalancing:ap-northeast-1:XXXX:targetgroup/ecs-canary-green/ZZZZ
        containerName: web
        containerPort: 80
  pipeline:
    stages:
      # Rollout CANARY variant's workload.
      # scale represents the percentage of workload will be rolled out,
      # in this case 30% of the current PRIMARY variant's workload is set.
      # Note: Rolled out variant serves no traffic at this time.
      - name: ECS_CANARY_ROLLOUT
        with:
          scale: 30
      # Change the traffic routing state where
      # the CANARY workloads will receive the specified percentage of traffic
      # (20% in this case). This is known as multi-phase canary strategy.
      - name: ECS_TRAFFIC_ROUTING
        with:
          canary: 20
      # Hold the deployment process for 150 seconds.
      - name: WAIT
        with:
          duration: 150s
      # Update the workload of PRIMARY variant to the new version.
      - name: ECS_PRIMARY_ROLLOUT
      # Change the traffic routing state where
      # the PRIMARY workloads will receive 100% of the traffic.
      - name: ECS_TRAFFIC_ROUTING
        with:
          primary: 100
      # Destroy all workloads of CANARY variant.
      - name: ECS_CANARY_CLEAN
