apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-run
  labels:
    app: script-run
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: script-run
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: script-run
        pipecd.dev/variant: primary
    spec:
      containers:
      - name: helloworld
        image: gcr.io/pipecd/helloworld:v0.45.0
        args:
          - server
        ports:
        - containerPort: 9085
