{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "piped.secretName" . }}
  labels:
    {{- include "piped.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
# Below ones will be removed in the future.
{{- if .Values.secret.pipedKey.data }}
  {{ .Values.secret.pipedKey.fileName }}: {{ .Values.secret.pipedKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.sshKey.data }}
  {{ .Values.secret.sshKey.fileName }}: {{ .Values.secret.sshKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.sealedSecretSealingKey.publicKey.data }}
  {{ .Values.secret.sealedSecretSealingKey.publicKey.fileName }}: {{ .Values.secret.sealedSecretSealingKey.publicKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.sealedSecretSealingKey.privateKey.data }}
  {{ .Values.secret.sealedSecretSealingKey.privateKey.fileName }}: {{ .Values.secret.sealedSecretSealingKey.privateKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.sealedSecretGCPKMS.encryptServiceAccount.data }}
  {{ .Values.secret.sealedSecretGCPKMS.encryptServiceAccount.fileName }}: {{ .Values.secret.sealedSecretGCPKMS.encryptServiceAccount.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.sealedSecretGCPKMS.decryptServiceAccount.data }}
  {{ .Values.secret.sealedSecretGCPKMS.decryptServiceAccount.fileName }}: {{ .Values.secret.sealedSecretGCPKMS.decryptServiceAccount.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.secretManagementKeyPair.publicKey.data }}
  {{ .Values.secret.secretManagementKeyPair.publicKey.fileName }}: {{ .Values.secret.secretManagementKeyPair.publicKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.secretManagementKeyPair.privateKey.data }}
  {{ .Values.secret.secretManagementKeyPair.privateKey.fileName }}: {{ .Values.secret.secretManagementKeyPair.privateKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.cloudRunCredentials.data }}
  {{ .Values.secret.cloudRunCredentials.fileName }}: {{ .Values.secret.cloudRunCredentials.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.awsCredentials.data }}
  {{ .Values.secret.awsCredentials.fileName }}: {{ .Values.secret.awsCredentials.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.datadogApiKey.data }}
  {{ .Values.secret.datadogApiKey.fileName }}: {{ .Values.secret.datadogApiKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.datadogApplicationKey.data }}
  {{ .Values.secret.datadogApplicationKey.fileName }}: {{ .Values.secret.datadogApplicationKey.data | b64enc | quote }}
{{- end }}
{{- if .Values.secret.kubeConfigs }}
{{- range .Values.secret.kubeConfigs }}
  {{ .fileName | quote }}: {{ .data | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
