{
 "title": "Node",
 "description": "For white-box monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (count(node_cpu_seconds_total{mode=\"system\"}) by (kubernetes_node))"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node - CPU Usage [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load Average [rate-5m]",
   "type": "graph",
   "description": "Note: Normalized by the number of CPUs\n\nPurpose: To know the saturation of CPU cores.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (node_load5)\n/\ncount(node_cpu_seconds_total{mode=\"system\"}) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (node_memory_MemTotal_bytes{job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Note: Non available RAM memory",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n(avg by (instance) (node_memory_MemAvailable_bytes) * 100)\n/\n(avg by (instance) (node_memory_MemTotal_bytes)))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / (1024 * 1024 * 1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Swap Used",
   "type": "graph",
   "description": "Purpose: To know the saturation of memory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)\n/\n(node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}