# Quick sync by rolling out the new version and switching all traffic to it.
# https://docs.aws.amazon.com/lambda/latest/dg/configuration-versions.html
apiVersion: pipecd.dev/v1beta1
kind: LambdaApp
spec:
  name: zip-packing-s3
  labels:
    env: example
    team: abc
