{
 "title": "Go",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Go Versioning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Go versions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version)(go_info{job=\"pipecd-ops\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Threads/Routines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "OS Threads of pipeds",
   "type": "graph",
   "description": "The number of OS threads spawned in pipeds instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (piped)(go_threads{job=\"pipecd-ops\"})",
     "legendFormat": "{{piped}}"
    }
   ]
  },
  {
   "title": "Number of Goroutines of pipeds",
   "type": "graph",
   "description": "The number of goroutines currently run in piped instances.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (piped)(go_goroutines{job=\"pipecd-ops\"})",
     "legendFormat": "{{piped}}"
    }
   ]
  },
  { "title": "Heap Stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Alloc",
   "type": "graph",
   "description": "Number of heap bytes allocated and still in use",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (piped) (go_memstats_heap_alloc_bytes{job=\"pipecd-ops\"} / (1024 * 1024))",
     "legendFormat": "{{piped}}"
    }
   ]
  },
  {
   "title": "Inuse",
   "type": "graph",
   "description": "Number of heap bytes that are in use",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (piped) (go_memstats_heap_inuse_bytes{job=\"pipecd-ops\"} / (1024 * 1024))",
     "legendFormat": "{{piped}}"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (piped) (go_memstats_heap_idle_bytes{job=\"pipecd-ops\"} / (1024 * 1024))",
     "legendFormat": "{{piped}}"
    }
   ]
  }
 ]
}