apiVersion: pipecd.dev/v1beta1
kind: AnalysisTemplate
spec:
  metrics:
    http_error_rate:
      interval: 1m
      provider: prometheus-dev
      expected:
        max: 0
      query: |
        sum by (job) (rate(http_requests_total{status=~"5.*", job="{{ .App.Name }}"}[1m]))
        /
        sum by (job) (rate(http_requests_total{job="{{ .App.Name }}"}[1m]))

    http_request_duration_99th_quantile:
      interval: 1m
      provider: prometheus-dev
      expected:
        max: 0.5
      query: |
        histogram_quantile(
          0.99,
          sum without (instance, job) (rate(http_request_duration_seconds_bucket{job="{{ .App.Name }}"}[1m]))
        )

    container_cpu_usage_seconds_total:
      interval: 1m
      provider: prometheus-dev
      failureLimit: 2
      expected:
        max: 20
      query: |
        sum by (job) (
          rate(container_cpu_usage_seconds_total{
            namespace="{{ .K8s.Namespace }}",
            pod="{{ .App.Name }}-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)"
          }[5m]) * 100
        )
