version: v1
kind: Plugin
spec:
  # A plugin that automatically creates issues when merging
  # pull request based on specified keywords.
  # See more: https://kapetanios.dev/docs/plugins/todo
  todo:
    enabled: true
    autoAssign: true

  cla:
    enabled: true
    url: "https://github.com/pipe-cd/pipecd/blob/master/CLA.md"
    skipUsers:
      - pipecd-bot
