{
 "title": "Go",
 "description": "For white-box monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "component", "query": "server,ops" }
  ]
 },
 "panels": [
  {
   "title": "Go version of $component",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (go_info{pipecd_component=\"$component\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "OS Thread of $component",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{pipecd_component=\"$component\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Stats of $component",
   "type": "graph",
   "description": "Heap metrics reported by Go",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pipecd_component) (go_memstats_heap_alloc_bytes{pipecd_component=\"$component\"} / (1024 * 1024))",
     "legendFormat": "alloc"
    },
    {
     "expr": "sum by (pipecd_component) (go_memstats_heap_inuse_bytes{pipecd_component=\"$component\"} / (1024 * 1024))",
     "legendFormat": "inuse"
    },
    {
     "expr": "sum by (pipecd_component) (go_memstats_heap_idle_bytes{pipecd_component=\"$component\"} / (1024 * 1024))",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "GC Duration Average of $component",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{pipecd_component=\"$component\"}[5m])\n/\nrate(go_gc_duration_seconds_count{pipecd_component=\"$component\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Goroutines of $component",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{pipecd_component=\"$component\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}