{
 "title": "Incoming Request",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "api",
    "query": {
     "query": "label_values(pipecd_grpc_service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/sec [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_method) (\n  rate(grpc_server_handled_total{pipecd_component=\"server\", pipecd_grpc_service=\"$api\"}[5m])\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "99th Quantile of Request Duration",
   "type": "graph",
   "description": "99th Quantile of Request Duration for each gRPC method",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum without(instance, job)(rate(pipecd_gateway_requests_duration_bucket{pipecd_grpc_service=\"$api\"}[5m]))\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Error Percentage by method",
   "type": "graph",
   "description": "Non-NotFound Error Percentage for each gRPC method",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_method) (\n  rate(grpc_server_handled_total{pipecd_component=\"server\", pipecd_grpc_service=\"$api\", grpc_code!=\"OK\", grpc_code!=\"NotFound\"}[5m])\n)\n/\nsum by (grpc_method) (\n  rate(grpc_server_handled_total{pipecd_component=\"server\", pipecd_grpc_service=\"$api\"}[5m])\n) * 100\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Error Percentage by code",
   "type": "graph",
   "description": "Non-NotFound Error Percentage for each gRPC method",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_code) (\n  rate(grpc_server_handled_total{pipecd_component=\"server\", pipecd_grpc_service=\"$api\", grpc_code!=\"OK\", grpc_code!=\"NotFound\"}[5m])\n)\n/\nsum by (grpc_code) (\n  rate(grpc_server_handled_total{pipecd_component=\"server\", pipecd_grpc_service=\"$api\"}[5m])\n) * 100\n",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Requests/sec [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (\n  rate(http_requests_total{pipecd_component=\"server\"}[5m])\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "5xx Error Percentage",
   "type": "graph",
   "description": "5xx Error Percentage for each path",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (\n  rate(http_requests_total{pipecd_component=\"server\", code=~\"5.*\"}[5m])\n)\n/\nsum by (path) (\n  rate(http_requests_total{pipecd_component=\"server\"}[5m])\n) * 100\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "99th Quantile of Request Duration",
   "type": "graph",
   "description": "99th Quantile of Request Duration for each path",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum without(instance, job)(rate(http_request_duration_milliseconds_bucket{pipecd_component=\"server\"}[5m]))\n)",
     "legendFormat": "{{path}}: {{code}}"
    }
   ]
  }
 ]
}