{
 "title": "Go",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "piped",
    "query": {
     "query": "label_values(go_info{pipecd_component=\"piped\"}, piped)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Threads/Routines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OS Threads",
   "type": "graph",
   "description": "The number of OS threads spawned in pipeds instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (piped)(go_threads{job=\"controlplane-ops\", pipecd_component=\"piped\", piped=~\"$piped\"})",
     "legendFormat": "{{piped}}"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "graph",
   "description": "The number of goroutines currently run in piped instances.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (piped)(go_goroutines{job=\"controlplane-ops\", pipecd_component=\"piped\", piped=~\"$piped\"})",
     "legendFormat": "{{piped}}"
    }
   ]
  },
  { "title": "Heap Stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Alloc",
   "type": "graph",
   "description": "Number of heap bytes allocated and still in use",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (piped) (go_memstats_heap_alloc_bytes{job=\"controlplane-ops\", pipecd_component=\"piped\", piped=~\"$piped\"} / (1024 * 1024))",
     "legendFormat": "{{piped}}"
    }
   ]
  },
  {
   "title": "Inuse",
   "type": "graph",
   "description": "Number of heap bytes that are in use",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (piped) (go_memstats_heap_inuse_bytes{job=\"controlplane-ops\", pipecd_component=\"piped\", piped=~\"$piped\"} / (1024 * 1024))",
     "legendFormat": "{{piped}}"
    }
   ]
  }
 ]
}