// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pkg/app/pipedv1/cmd/piped/service/service.proto

package service

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DecryptSecretRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DecryptSecretRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DecryptSecretRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DecryptSecretRequestMultiError, or nil if none found.
func (m *DecryptSecretRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DecryptSecretRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetSecret()) < 1 {
		err := DecryptSecretRequestValidationError{
			field:  "Secret",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DecryptSecretRequestMultiError(errors)
	}

	return nil
}

// DecryptSecretRequestMultiError is an error wrapping multiple validation
// errors returned by DecryptSecretRequest.ValidateAll() if the designated
// constraints aren't met.
type DecryptSecretRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DecryptSecretRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DecryptSecretRequestMultiError) AllErrors() []error { return m }

// DecryptSecretRequestValidationError is the validation error returned by
// DecryptSecretRequest.Validate if the designated constraints aren't met.
type DecryptSecretRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DecryptSecretRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DecryptSecretRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DecryptSecretRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DecryptSecretRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DecryptSecretRequestValidationError) ErrorName() string {
	return "DecryptSecretRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DecryptSecretRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDecryptSecretRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DecryptSecretRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DecryptSecretRequestValidationError{}

// Validate checks the field values on DecryptSecretResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DecryptSecretResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DecryptSecretResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DecryptSecretResponseMultiError, or nil if none found.
func (m *DecryptSecretResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DecryptSecretResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DecryptedSecret

	if len(errors) > 0 {
		return DecryptSecretResponseMultiError(errors)
	}

	return nil
}

// DecryptSecretResponseMultiError is an error wrapping multiple validation
// errors returned by DecryptSecretResponse.ValidateAll() if the designated
// constraints aren't met.
type DecryptSecretResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DecryptSecretResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DecryptSecretResponseMultiError) AllErrors() []error { return m }

// DecryptSecretResponseValidationError is the validation error returned by
// DecryptSecretResponse.Validate if the designated constraints aren't met.
type DecryptSecretResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DecryptSecretResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DecryptSecretResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DecryptSecretResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DecryptSecretResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DecryptSecretResponseValidationError) ErrorName() string {
	return "DecryptSecretResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DecryptSecretResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDecryptSecretResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DecryptSecretResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DecryptSecretResponseValidationError{}
