{
 "title": "Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "project",
    "query": {
     "query": "label_values(insight_application_total{pipecd_component=\"ops\"}, project)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Activated applications",
   "type": "stat",
   "description": "Total number of activated applications",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (insight_application_total{pipecd_component=\"ops\", project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Sum by kind",
   "type": "stat",
   "description": "Number of activated applications sum by kind",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (app_kind) (insight_application_total{pipecd_component=\"ops\", project=~\"$project\"})",
     "legendFormat": "{{app_kind}}"
    }
   ]
  },
  {
   "title": "Applications by project",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum without (pipecd_component, instance, job) (insight_application_total{pipecd_component=\"ops\", project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Sum by project",
   "type": "bargauge",
   "description": "Number activated applications sum by project",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (project) (insight_application_total{pipecd_component=\"ops\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total completed Deployments [24h]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(deployment_status{pipecd_component=\"piped\",project=~\"$project\",status=~\"DEPLOYMENT_CANCELLED|DEPLOYMENT_SUCCESS|DEPLOYMENT_FAILURE\"}[24h])))"
    }
   ]
  },
  {
   "title": "Total triggered deployments [24h]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(grpcapi_create_deployment_total{project=~\"$project\"}[24h])))"
    }
   ]
  },
  {
   "title": "Deployments count by project [24h]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (project) (round(increase(grpcapi_create_deployment_total[24h])))",
     "legendFormat": "{{project}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Cache hit ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(source) (rate(cache_get_operation_total{status=\"hit\", pipecd_component=\"server\"}[5m]))\n/\nsum by(source) (rate(cache_get_operation_total{pipecd_component=\"server\"}[5m])\n)\n* 100",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}