# Deployment pipeline that contains a manual approval stage.
apiVersion: pipecd.dev/v1beta1
kind: LambdaApp
spec:
  name: wait-approval
  pipeline:
    stages:
      # Deploy workloads of the new version.
      # But this is still receiving no traffic.
      - name: LAMBDA_CANARY_ROLLOUT
      # Promote new version to receive amount of traffic.
      - name: LAMBDA_PROMOTE
        with:
          percent: 10
      - name: WAIT_APPROVAL
      # Promote new version to receive all traffic.
      - name: LAMBDA_PROMOTE
        with:
          percent: 100
  notification:
    mentions:
      - event: DEPLOYMENT_WAIT_APPROVAL
        slack:
          - slack-user-id-1  # slack-user-name-1
          - slack-user-id-2  # slack-user-name-2
      # Specifying "*" means mentioning the given users for all events.
      - event: "*"
        slack:
          - slack-user-id-3  # slack-user-name-3
