{
 "title": "Pods",
 "description": "For white-box monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage of $service Pod [rate-5m]",
   "type": "graph",
   "description": "CPU usage per Pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(service) (\n  rate(container_cpu_usage_seconds_total{\n    service=\"$service\"\n  }[5m]) * 100\n)",
     "legendFormat": "$service"
    }
   ]
  },
  {
   "title": "Memory Usage of $service Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(service) (\n  container_memory_usage_bytes{\n    service=\"$service\"\n  } / (1024 * 1024)\n)",
     "legendFormat": "$service"
    }
   ]
  },
  {
   "title": "Restart number of $service Pod [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(kube_pod_container_status_restarts_total{service=\"$service\"}[5m]))",
     "legendFormat": "$service"
    }
   ]
  }
 ]
}