{
 "title": "gRPC Incoming Request",
 "description": "For black-box monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "api",
    "query": {
     "query": "label_values(envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests/sec [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(envoy_response_code,instance,job) (rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"$api\"}[5m]))",
     "legendFormat": "$api"
    }
   ]
  },
  {
   "title": "Non-4xx Error Percentage",
   "type": "graph",
   "description": "Non-4xx Error Percentage  for each gRPC method",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(envoy_cluster_name) (rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=~\"5\", job=\"pipecd-gateway\", envoy_cluster_name=\"$api\"}[5m]))\n/\nsum by(envoy_cluster_name) (rate(envoy_cluster_upstream_rq_xx{job=\"pipecd-gateway\", envoy_cluster_name=\"$api\"}[5m]))\n* 100 or on() vector(0)",
     "legendFormat": "$api"
    }
   ]
  },
  {
   "title": "99th Quantile of Request Duration",
   "type": "graph",
   "description": "99th Quantile of Request Duration for each gRPC method",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum without(instance, job)(rate(pipecd_gateway_requests_duration_bucket{envoy_cluster_name=\"$api\"}[5m]))\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "99th Quantile of Request Size",
   "type": "graph",
   "description": "99th quantile of request size per gRPC method",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum without(instance, job)(rate(envoy_cluster_upstream_rq_body_size_bucket{envoy_cluster_name=\"$api\"}[5m]))\n) * (1024 * 1024)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "99th Quantile of Response Size",
   "type": "graph",
   "description": "99th quantile of response size per gRPC method",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum without(instance, job)(rate(envoy_cluster_upstream_rs_body_size_bucket{envoy_cluster_name=\"$api\"}[5m]))\n) * (1024 * 1024)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}