{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Activated applications",
   "type": "stat",
   "description": "Total number of activated applications",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (insight_application_total{pipecd_component=\"ops\"})"
    }
   ]
  },
  {
   "title": "Sum by kind",
   "type": "stat",
   "description": "Number of activated applications sum by kind",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (app_kind) (insight_application_total{pipecd_component=\"ops\"})",
     "legendFormat": "{{app_kind}}"
    }
   ]
  },
  {
   "title": "Sum by project",
   "type": "graph",
   "description": "Number activated applications sum by project",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (project) (insight_application_total{pipecd_component=\"ops\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cache hit ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(source) (rate(cache_get_operation_total{status=\"hit\", pipecd_component=\"server\"}[5m]))\n/\nsum by(source) (rate(cache_get_operation_total{pipecd_component=\"server\"}[5m])\n)\n* 100",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}