// Copyright 2024 The PipeCD Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package model;
option go_package = "github.com/pipe-cd/pipecd/pkg/model";

import "google/protobuf/descriptor.proto";
import "pkg/model/project.proto";

// RBAC is a gRPC method option describing the RBAC resource/action an RPC
// requires, or that the RPC should bypass RBAC checks entirely.
message RBAC {
    // The resource type the caller must be authorized on. Ignored if `ignored` is true.
    model.ProjectRBACResource.ResourceType resource = 1;
    // The action the caller must be authorized to perform. Ignored if `ignored` is true.
    model.ProjectRBACPolicy.Action action = 2;
    // Whether the RBAC check should be skipped entirely for this RPC.
    bool ignored = 3;
}

extend google.protobuf.MethodOptions {
    RBAC rbac = 59091;
}
