# Deploy a helm chart sourced from a Helm Chart Repository without using pipeline.
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    # Helm chart sourced from a Helm Chart Repository.
    helmChart:
      repository: pipecd
      name: helloworld
      version: v0.10.0
    helmOptions:
      valueFiles:
        - values.yaml
      releaseName: helm-remote-chart
    helmVersion: 3.1.1
