{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active piped",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (go_info{job=\"pipecd-ops\", pipecd_component=\"piped\"})"
    }
   ]
  },
  {
   "title": "Running versions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (piped_version)(go_info{job=\"pipecd-ops\", pipecd_component=\"piped\"})",
     "legendFormat": "{{piped_version}}"
    }
   ]
  },
  {
   "title": "Piped list",
   "type": "table",
   "description": "List all activated pipeds",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum without (instance, job, pipecd_component) (go_info{job=\"pipecd-ops\", pipecd_component=\"piped\"})"
    }
   ]
  }
 ]
}