name: cherry_pick

on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        description: 'release branch (e.g. release-v0.48.x)'
        required: true
        type: string
      version:
        description: 'release version (e.g. v0.48.1)'
        required: true
        type: string
jobs:
  tool:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: make a cherry-pick PR
        run: |
          git config user.name "pipecd-bot"
          git config user.email "pipecd.dev@gmail.com"
          #
          # --limit 100 is to avoid the case where the number of PRs which included in a patch exceeds the default limit (30)
          # if the number of PRs exceeds 100, the cherry-pick command will fail
          #
          ./hack/cherry-pick.sh -q ${{ inputs.releaseBranch }} $(gh pr list --label cherry-pick --label ${{ inputs.version }} --state merged --limit 100 | awk '{print $1}' | sort | paste -sd ' ' -)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
