name: CodeGen

on:
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    name: Validate Generated Code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Generate code
      uses: docker://gcr.io/pipecd/codegen@sha256:088a403140a0fbed7d71270019edb81f073d2b4fa139f9046a453cd76b6e0384 #v0.6.0
      with:
        args: /github/workspace
    - name: Show Git status
      shell: bash
      run: git status
    - name: Validate
      shell: bash
      run: test -z "$(git status --porcelain)"
