name: docs-lint

on:
  pull_request:
    paths:
      - "docs/**"
      - ".markdownlint-cli2.yaml"
      - ".github/workflows/docs-lint.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2
      - name: Run markdownlint
        run: markdownlint-cli2 "docs/content/en/docs-dev/**/*.md"
