name: gen

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  code:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Generate code
      # NOTE: Keep this container image as same as defined in Makefile
      uses: docker://ghcr.io/pipe-cd/codegen@sha256:8b17498a7cfb58fbaf403ec7cab01a740238aaee43d030e65a40abb710f9e68a # v0.56.0-30-g0d71fd0
      with:
        entrypoint: ./tool/codegen/codegen.sh
        args: /github/workspace
    - name: Show Git status
      shell: bash
      run: git status
    - name: Validate
      shell: bash
      run: test -z "$(git status --porcelain)"
