name: prerelease

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
    paths:
      - 'RELEASE'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  gh-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: pipe-cd/actions-gh-release@v2.6.0
        with:
          release_file: 'RELEASE'
          token: ${{ secrets.GITHUB_TOKEN }}
