name: Publish

on:
  push:
    tags:
    - 'v*'

env:
  GO_VERSION: 1.17.6

jobs:
  gh_release:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      - run: echo "not implemented"

  binary:
    name: Binary
    runs-on: ubuntu-latest
    needs: gh_release
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Determine version
        run: echo "PIPECD_VERSION=$(git describe --tags --always --abbrev=7)" >> $GITHUB_ENV

      - name: Build binary artifacts
        run: |
          make build/go MOD=piped BUILD_OS=linux BIN_SUFFIX=${{ env.PIPECD_VERSION }}_linux_amd64
          make build/go MOD=piped BUILD_OS=darwin BIN_SUFFIX=${{ env.PIPECD_VERSION }}_darwin_amd64
          make build/go MOD=pipectl BUILD_OS=linux BIN_SUFFIX=${{ env.PIPECD_VERSION }}_linux_amd64
          make build/go MOD=pipectl BUILD_OS=darwin BIN_SUFFIX=${{ env.PIPECD_VERSION }}_darwin_amd64

      - name: Publish binary artifacts
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 #v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            piped_${{ env.PIPECD_VERSION }}_linux_amd64
            piped_${{ env.PIPECD_VERSION }}_darwin_amd64
            pipectl_${{ env.PIPECD_VERSION }}_linux_amd64
            pipectl_${{ env.PIPECD_VERSION }}_darwin_amd64
