name: publish

on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: 1.22.4

jobs:
  gh_release:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "not implemented"

  binary:
    runs-on: ubuntu-24.04
    needs: gh_release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Determine version
        run: echo "PIPECD_VERSION=$(git describe --tags --always --abbrev=7)" >> $GITHUB_ENV

      - name: Build binary artifacts
        run: |
          make build/go MOD=piped BUILD_OS=linux BUILD_ARCH=amd64 BIN_SUFFIX=_${{ env.PIPECD_VERSION }}_linux_amd64
          make build/go MOD=piped BUILD_OS=linux BUILD_ARCH=arm64 BIN_SUFFIX=_${{ env.PIPECD_VERSION }}_linux_arm64
          make build/go MOD=piped BUILD_OS=darwin BUILD_ARCH=amd64 BIN_SUFFIX=_${{ env.PIPECD_VERSION }}_darwin_amd64
          make build/go MOD=piped BUILD_OS=darwin BUILD_ARCH=arm64 BIN_SUFFIX=_${{ env.PIPECD_VERSION }}_darwin_arm64
          make build/go MOD=pipectl BUILD_OS=linux BUILD_ARCH=amd64 BIN_SUFFIX=_${{ env.PIPECD_VERSION }}_linux_amd64
          make build/go MOD=pipectl BUILD_OS=linux BUILD_ARCH=arm64 BIN_SUFFIX=_${{ env.PIPECD_VERSION }}_linux_arm64
          make build/go MOD=pipectl BUILD_OS=darwin BUILD_ARCH=amd64 BIN_SUFFIX=_${{ env.PIPECD_VERSION }}_darwin_amd64
          make build/go MOD=pipectl BUILD_OS=darwin BUILD_ARCH=arm64 BIN_SUFFIX=_${{ env.PIPECD_VERSION }}_darwin_arm64

      - name: Publish binary artifacts
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda #v2.2.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./.artifacts/piped_${{ env.PIPECD_VERSION }}_linux_amd64
            ./.artifacts/piped_${{ env.PIPECD_VERSION }}_linux_arm64
            ./.artifacts/piped_${{ env.PIPECD_VERSION }}_darwin_amd64
            ./.artifacts/piped_${{ env.PIPECD_VERSION }}_darwin_arm64
            ./.artifacts/pipectl_${{ env.PIPECD_VERSION }}_linux_amd64
            ./.artifacts/pipectl_${{ env.PIPECD_VERSION }}_linux_arm64
            ./.artifacts/pipectl_${{ env.PIPECD_VERSION }}_darwin_amd64
            ./.artifacts/pipectl_${{ env.PIPECD_VERSION }}_darwin_arm64
