name: Publish Artifacts

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'

      - name: Build pipecd binary
        run: GOOS=linux GOARCH=amd64 go build -o ./.artifacts/pipecd ./cmd/pipecd
      - name: Build piped binary
        run: GOOS=linux GOARCH=amd64 go build -o ./.artifacts/piped ./cmd/piped
      - name: Build launcher binary
        run: GOOS=linux GOARCH=amd64 go build -o ./.artifacts/launcher ./cmd/launcher
      - name: Build pipectl binary
        run: GOOS=linux GOARCH=amd64 go build -o ./.artifacts/pipectl ./cmd/pipectl
      - name: Build helloworld binary
        run: GOOS=linux GOARCH=amd64 go build -o ./.artifacts/helloworld ./cmd/helloworld

      - name: Log in to the container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push pipecd image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          file: cmd/pipecd/Dockerfile
          tags: ${{ env.REGISTRY }}/pipe-cd/pipecd:${{ github.ref_name }}
      - name: Build and push piped image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          file: cmd/piped/Dockerfile
          tags: ${{ env.REGISTRY }}/pipe-cd/piped:${{ github.ref_name }}
      - name: Build and push launcher image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          file: cmd/launcher/Dockerfile
          tags: ${{ env.REGISTRY }}/pipe-cd/launcher:${{ github.ref_name }}
      - name: Build and push pipectl image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          file: cmd/pipectl/Dockerfile
          tags: ${{ env.REGISTRY }}/pipe-cd/pipectl:${{ github.ref_name }}
      - name: Build and push helloworld image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          file: cmd/helloworld/Dockerfile
          tags: ${{ env.REGISTRY }}/pipe-cd/helloworld:${{ github.ref_name }}
